### ISSUE TITLE
Failed to run sample code  bwgemmkernel.c in path 'libxsmm/samples/xgemmkernel'

### ISSUE THREAD

**Issue by fightbob** [hfp/libxsmm#174] opened 2017-05-26 09:42 UTC
1.  in home directory, run '_make_' to build the project
 2. go to _libxsmm/samples/xgemmkernel,_ run '_make_' to build the sample code
 3. in the path of _libxsmm/samples/xgemmkernel_, run '_test_bwgemmkernel.sh_', it's successful. But failed, 
 when run '_./bwgemmkernel 49 5 25 49 25 49 1 1 0 0 nopf I16 10000_'. The response information is:

RUNNING (49x25) X (25x5) = (49x5),  int16
0.036524s for C
3.353936 GOPS for C
function pointer address: 0
JIT failed, please run with LIBXSMM_VERBOSE=-1 and/or with debug mode LIBXSMM library!

Why the function pointer address is **_ZERO_**?

**Comment by alheinecke** [comment] 2017-05-26 10:20
The bwgemmkernel today is a driver for only the wgemm kernel (int16 A, int16 B, int32 C) and is a very early prototype. Its targets are machine learning applications and it's highly tailored towards the Intel instruction set which specifies horizontal additions for integer vector multiplication. That means A is expected to be block by a factor of 2 along the K dimension, instead of A[k][m] for wgemm A needs to be in A[k/2][M][2] format and B in B[n][k] format. The 32bit result is returned in C[n][m] format. So B and C can remain in classic col-major format. 
Although already SSE2 offered instructions to run such a multiplication efficiently on IA, our current implementation is limited to future Intel processors providing AVX512_4VNNIW instruction set extensions, c.f. https://patchwork.kernel.org/patch/9373649/ . Adding backward support (AVX512BW) is planed for near future. AVX2 support is currently not planned for int16 gemm.

**Comment by fightbob** [comment] 2017-05-26 14:53
@alheinecke Thanks a lot! Is any benchmark code for int16? Or how can I test int16 performance? Benchmark, based on another  similar open library https://github.com/google/gemmlowp, shows slower MM speed than MKL. Maybe MM speed of LIBXSMM int16 feature is better than gemmlowp. However, it needs test result about LIBXSMM int16 to compare the performance. Thanks again!

**Comment by hfp** [comment] 2017-05-26 15:18
As Alex said, QVNNI is currently required and becomes available with "Knights Mill" (KNM). The latter is a Xeon Phi derivative, which targets Machine Learning. The planned support for AVX512BW is/becomes available with the new Xeon generation (non-Phi) codenamed "Skylake Server" (SKX).

**Comment by fightbob** [comment] 2017-05-26 15:24
@hfp I run the bwgemmkernel code in Skylake server, but still failed with the same error.

**Comment by alheinecke** [comment] 2017-05-26 15:41
So you have access to a Skylake part that can run AVX512? Skylake Server is not Xeon E3.

**Comment by hfp** [comment] 2017-05-26 17:09
Maybe it is possible to give some throughput numbers for QVNNI and AVX512bw normalized to clock frequency and normalized/based on AVX2.

**Comment by heagoo** [comment] 2017-05-27 01:22
We are very interested in the int16 support, as we found it can achieve nearly the same accuracy by converting float32 to int16 for DNN algorithms. So, when will AVX512BW be available? And how about the performance estimation compared with float32?
(BTW: we are doing testing on Skylake server)

**Comment by alheinecke** [comment] 2017-05-27 11:54
At this point I provide performance estimations here. But please reach out privately and then we can go from there.
Hard numbers aside and having our Skylake Server convolution code in mind: Using AVX512BW for integer matrix multiplication will for sure end up in more instructions than using FP32. There reason for this is that AVX512BW doesn't offer a multiply+accumulate instruction.
-> What is one instruction for F32 are two instructions for int16. With AVX512_4VNNIW and AVX512_4FMA the number of instructions needed for F32 and int16 are the same as AVX512_4VNNIW also accumulates with the destination register.
Note: We are also planning to provide int8 kernels with int32 accumulate (the bwgemmkernel.c file already has some preparation for this) using AVX512BW. A full int8->int32 multiply accumulate takes three instructions using AVX512BW.
Note2: are you interested in int8/int16 convolution kernels provided in LIBXSMM?

**Comment by heagoo** [comment] 2017-05-31 01:57
Got you.
And yes, we are also interested in int8/int16 convolution kernels, if it can provide a great performance boost. But when will it be available? (I mean supported by AVX512BW)

**Comment by jeffhammond** [comment] 2017-06-27 17:03
I wonder if you are not seeing AVX-512BW support in your Skylake server system because the toolchain does not support the instructions.  Have you confirmed that your binutils supports these instructions?  Perhaps you can write a trivial code that invokes AVX-512BW via inline assembly or [intrinsics](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#avx512techs=AVX512BW) to verify that you can link and run such a program.

I recall having issues with lack of AVX2 ISA support in the default binutils for Linux and MacOS when Haswell was new, but in both cases it was addressed by updating the toolchain.

**Comment by alheinecke** [comment] 2017-06-27 17:07
Not sure what you mean, nothing in that thread is about messing AVX512BW in linux.

**Comment by hfp** [comment] 2017-06-27 17:43
( Maybe this was [partly] meant to comment on issue #171. )

**Comment by hfp** [comment] 2018-03-03 19:55
The xgemmkernel sample code has been moved into samples/xgemm now hosting "xgemm" and "kernel". The latter (the former xgemmkernel) is essentially a straight-forward/limited implementation of GEMM for alpha=beta=1; it uses a fixed tile sizes and a single kernel for this tile. The built-in libxsmm_gemm_omp (hosted by libxsmmext library) is what's demonstrated by the "xgemm" sample code (the big brother of "kernel" with less limitation).

I will close this issue as we rework general tiling (libxsmm_gemm_omp), BGEMM, and low-precision support. If there is anything else more specific, please feel free to report an issue!

**Closed by hfp** 2018-03-03 19:55 UTC
