### ISSUE TITLE
Handle with NULL kernel returned by libxsmm_dfsspmdm_create

### ISSUE THREAD

**Issue by FreddieWitherden** [hfp/libxsmm#455] opened 2021-01-19 22:59 UTC
Using the master branch compiled with `make SHARED=1 NOBLAS=1 ` the function `libxsmm_dfsspmdm_create` is returning a pointer to a structure whose kernel member is NULL when passed a dense A matrix with M = 9, N = 48, and K = 16, lda = 16, ldb = 624, ldc = 624.  Specifically, the call at:

https://github.com/hfp/libxsmm/blob/716e20323b50a178b56c51754fae58e0df2fa2cf/src/libxsmm_fsspmdm.c#L98

fails to yield a kernel (which is perhaps not unexpected given A is dense) and so the else branch at:

https://github.com/hfp/libxsmm/blob/716e20323b50a178b56c51754fae58e0df2fa2cf/src/libxsmm_fsspmdm.c#L121

is triggered.  This should try and JIT a dense kernel here:

https://github.com/hfp/libxsmm/blob/716e20323b50a178b56c51754fae58e0df2fa2cf/src/libxsmm_fsspmdm.c#L123

but this returns a NULL pointer.  I am unsure if this is expected behaviour (and so the bug is in the create routine for not catching this), or if it is an issue with `libxsmm_dmmdispatch` that is causing it to fail to generate a dispatch routine.

**Comment by alheinecke** [comment] 2021-01-24 02:18
I cannot reproduce this issue with samples/pyfr.

I have created a file dense.mtx:
%%MatrixMarket matrix coordinate real general
%
9 16 144
1 1 1.0
1 2 1.0
1 3 1.0
1 4 1.0
1 5 1.0
1 6 1.0
1 7 1.0
1 8 1.0
1 9 1.0
1 10 1.0
1 11 1.0
1 12 1.0
1 13 1.0
1 14 1.0
1 15 1.0
1 16 1.0
2 1 1.0
2 2 1.0
2 3 1.0
2 4 1.0
2 5 1.0
2 6 1.0
[...]
9 9 1.0
9 10 1.0
9 11 1.0
9 12 1.0
9 13 1.0
9 14 1.0
9 15 1.0
9 16 1.0

and run "sde64 -skx -- ./pyfr_driver_asp_reg dense.mtx 48 1" and it passes without issues.

How to reproduce with pyfr_driver_asp_reg application?

**Comment by FreddieWitherden** [comment] 2021-01-24 03:11
I got around to building a debug build of libxsmm and have got to the bottom of the issue.  More recent versions of PyFR have been employing matrix multiplications with alpha != 1, which is currently unsupported by `libxsmm_dfsspmdm_create` (and hence triggers an assertion in debug mode).

Good news is that since our A matrices are constant this is a trivial fix; multiply through by alpha on
https://github.com/hfp/libxsmm/blob/716e20323b50a178b56c51754fae58e0df2fa2cf/src/libxsmm_fsspmdm.c#L83 and
https://github.com/hfp/libxsmm/blob/716e20323b50a178b56c51754fae58e0df2fa2cf/src/libxsmm_fsspmdm.c#L128
and then when calling `libxsmm_dmmdispatch` just pass a pointer to `double falpha = 1.0`.

**Comment by FreddieWitherden** [comment] 2021-01-24 03:24
I think this should do it:
```
diff --git a/src/libxsmm_fsspmdm.c b/src/libxsmm_fsspmdm.c
index 7ec83df48..841c167f5 100644
--- a/src/libxsmm_fsspmdm.c
+++ b/src/libxsmm_fsspmdm.c
@@ -19,6 +19,7 @@ LIBXSMM_API libxsmm_dfsspmdm* libxsmm_dfsspmdm_create(
   const double alpha, const double beta, libxsmm_blasint c_is_nt,
   const double* a_dense)
 {
+  double one = 1.0;
   double* a_csr_values = 0;
   unsigned int* a_csr_rowptr = 0;
   unsigned int* a_csr_colidx = 0;
@@ -32,7 +33,6 @@ LIBXSMM_API libxsmm_dfsspmdm* libxsmm_dfsspmdm_create(
   /* some checks... */
   assert(N % 16 == 0);
   assert(N >= 16);
-  assert(LIBXSMM_FEQ(alpha, 1.0));
   assert(LIBXSMM_FEQ(beta, 1.0) || LIBXSMM_FEQ(beta, 0.0));
   assert(K <= lda);
   assert(N <= ldc);
@@ -80,7 +80,7 @@ LIBXSMM_API libxsmm_dfsspmdm* libxsmm_dfsspmdm_create(
       a_csr_rowptr[i] = n;
       for (j = 0; j < K; j++) {
         if (LIBXSMM_NEQ(a_dense[(i*lda) + j], 0.0)) {
-          a_csr_values[n] = a_dense[(i*lda) + j];
+          a_csr_values[n] = alpha*a_dense[(i*lda) + j];
           a_csr_colidx[n] = j;
           n++;
         }
@@ -92,7 +92,7 @@ LIBXSMM_API libxsmm_dfsspmdm* libxsmm_dfsspmdm_create(
     new_handle->N_chunksize = 8;
 
     xgemm_desc = libxsmm_dgemm_descriptor_init(&xgemm_blob, M, new_handle->N_chunksize, K,
-      0, ldb, ldc, alpha, beta, flags, prefetch);
+      0, ldb, ldc, one, beta, flags, prefetch);
 
     if (0 != xgemm_desc) {
       new_handle->kernel = libxsmm_create_dcsr_reg(xgemm_desc, a_csr_rowptr, a_csr_colidx, a_csr_values);
@@ -120,12 +120,12 @@ LIBXSMM_API libxsmm_dfsspmdm* libxsmm_dfsspmdm_create(
   /* attempt to JIT dense kernel as sparse_reg failed */
   } else {
     new_handle->N_chunksize = 16;
-    new_handle->kernel = libxsmm_dmmdispatch(new_handle->N_chunksize, M, K, &ldb, &K, &ldc, &alpha, &beta, &flags, (const int*)LIBXSMM_GEMM_PREFETCH_NONE);
+    new_handle->kernel = libxsmm_dmmdispatch(new_handle->N_chunksize, M, K, &ldb, &K, &ldc, &one, &beta, &flags, (const int*)LIBXSMM_GEMM_PREFETCH_NONE);
     /* copy A over */
     new_handle->a_dense = (double*)libxsmm_aligned_malloc((size_t)M * (size_t)K * sizeof(double), 64);
     for ( i = 0; i < M; ++i ) {
       for ( j = 0; j < K; ++j ) {
-        new_handle->a_dense[(i*K)+j] = a_dense[(i*lda)+j];
+        new_handle->a_dense[(i*K)+j] = alpha*a_dense[(i*lda)+j];
       }
     }
   }
@@ -145,6 +145,7 @@ LIBXSMM_API libxsmm_sfsspmdm* libxsmm_sfsspmdm_create(
   const float alpha, const float beta, libxsmm_blasint c_is_nt,
   const float* a_dense)
 {
+  float one = 1.0f;
   float* a_csr_values = 0;
   unsigned int* a_csr_rowptr = 0;
   unsigned int* a_csr_colidx = 0;
@@ -158,7 +159,6 @@ LIBXSMM_API libxsmm_sfsspmdm* libxsmm_sfsspmdm_create(
   /* some checks... */
   assert(N % 16 == 0);
   assert(N >= 16);
-  assert(LIBXSMM_FEQ(alpha, 1.0f));
   assert(LIBXSMM_FEQ(beta, 1.0f) || LIBXSMM_FEQ(beta, 0.0f));
   assert(K <= lda);
   assert(N <= ldc);
@@ -206,7 +206,7 @@ LIBXSMM_API libxsmm_sfsspmdm* libxsmm_sfsspmdm_create(
       a_csr_rowptr[i] = n;
       for (j = 0; j < K; j++) {
         if (LIBXSMM_NEQ(a_dense[(i*lda) + j], 0.0f)) {
-          a_csr_values[n] = a_dense[(i*lda) + j];
+          a_csr_values[n] = alpha*a_dense[(i*lda) + j];
           a_csr_colidx[n] = j;
           n++;
         }
@@ -218,7 +218,7 @@ LIBXSMM_API libxsmm_sfsspmdm* libxsmm_sfsspmdm_create(
     new_handle->N_chunksize = 16;
 
     xgemm_desc = libxsmm_sgemm_descriptor_init(&xgemm_blob, M, new_handle->N_chunksize, K,
-      0, ldb, ldc, alpha, beta, flags, prefetch);
+      0, ldb, ldc, one, beta, flags, prefetch);
 
     if (0 != xgemm_desc) {
       new_handle->kernel = libxsmm_create_scsr_reg(xgemm_desc, a_csr_rowptr, a_csr_colidx, a_csr_values);
@@ -244,12 +244,12 @@ LIBXSMM_API libxsmm_sfsspmdm* libxsmm_sfsspmdm_create(
   /* attempt to JIT dense kernel as sparse_reg failed */
   } else {
     new_handle->N_chunksize = 16;
-    new_handle->kernel = libxsmm_smmdispatch(new_handle->N_chunksize, M, K, &ldb, &K, &ldc, &alpha, &beta, &flags, (const int*)LIBXSMM_GEMM_PREFETCH_NONE);
+    new_handle->kernel = libxsmm_smmdispatch(new_handle->N_chunksize, M, K, &ldb, &K, &ldc, &one, &beta, &flags, (const int*)LIBXSMM_GEMM_PREFETCH_NONE);
     /* copy A over */
     new_handle->a_dense = (float*)libxsmm_aligned_malloc((size_t)M * (size_t)K * sizeof(float), 64);
     for ( i = 0; i < M; ++i ) {
       for ( j = 0; j < K; ++j ) {
-        new_handle->a_dense[(i*K)+j] = a_dense[(i*lda)+j];
+        new_handle->a_dense[(i*K)+j] = alpha*a_dense[(i*lda)+j];
       }
     }
   }
```

**Comment by alheinecke** [comment] 2021-01-24 04:27
LGTM, can you submit a PR?

**Comment by FreddieWitherden** [comment] 2021-01-24 14:51
> LGTM, can you submit a PR?

Done.  Also, looking through the code I am wondering how hard the restriction that N has to be divisible by 16 is in the double precision case?  This currently prevents us from using XSMM under certain circumstances since we try to align based on vector length (8 elements for double, 16 for single).

**Comment by alheinecke** [comment] 2021-01-24 21:25
yes, I have pushed the straightforward changes in https://github.com/hfp/libxsmm/commit/15328f53a78cdf2c4c20d51af70296d638a8ed4e . However, this only will be useful when N/#cores is <16. 
We could also think about using masking, then arbitrary values for N would be possible. Right now N%8==0 is required for F64 and N%16==0 for F32.

**Comment by FreddieWitherden** [comment] 2021-01-24 21:47
At the moment in PyFR we JIT a primary kernel with N = 48 (for both single and double precision) and then, if N % 48 != 0, we also JIT a clean up kernel with N = 16 or 32 to handle whatever is left.  However, as we only enforce cache-line alignment with double precision we can sometimes have clean-up sizes which are not divisible by 16 and hence can not use XSMM in these situations (unless the user switches to 128 byte alignment, which can have negative consequences).  This change ensures we can always use XSMM.

**Comment by alheinecke** [comment] 2021-01-24 22:05
I see and yes for remainder handling this is helpful. I'm closing this issue for now.

**Closed by alheinecke** 2021-01-24 22:05 UTC
