### ISSUE TITLE
LIBXSMM scalability problems on NUMA system

### ISSUE THREAD

**Issue by ErikP94** [hfp/libxsmm#396] opened 2020-07-27 08:46 UTC
Hi,

we are using LibXSMM with OpenMP as discussed in Issue #353. As a qucik reminder, both of the following versions could be used in principle and were tested for this issue:

```bash
! in Fortran, the  save attribute forces xmm to be shared among OpenMP threads 
TYPE(LIBXSMM_DMMFUNCTION), save :: xmm
!$omp single
CALL libxsmm_dispatch(xmm, m, n, k)
!$omp end single
IF (libxsmm_available(xmm)) THEN
  !$omp do
  DO i = LBOUND(c, 3), UBOUND(c, 3)
    CALL libxsmm_dmmcall(xmm, a(:,:,i), b(:,:,i), c(:,:,i))
  END DO
END IF
```

or with the handle as a shared variable:

```bash
! in Fortran, the  save attribute forces xmm to be shared among OpenMP threads 
TYPE(LIBXSMM_DMMFUNCTION), save :: xmm
!$omp single
CALL libxsmm_dispatch(xmm, m, n, k)
!$omp end single
IF (libxsmm_available(xmm)) THEN
  !$omp do
  DO i = LBOUND(c, 3), UBOUND(c, 3)
    CALL libxsmm_dmmcall(xmm, a(:,:,i), b(:,:,i), c(:,:,i))
  END DO
END IF
```
Since issue #353 was resolved, OpenMP parallelization has worked without errors. However, the speedup does not scale with the number of threads when calculating on multiple sockets.
For example, I did a test on an Intel Haswell node on our high performance computer. This node contains 2 Intel Xeon CPU E5-2680 v3 (12 cores). The performance scales well, up to many threads are used. Even if this could have something to do with the First Touch principle and thus would be a known NUMA problem, this does not happen if we use our other two versions of matrix multiplication, which do not use LibXSMM.

The tests were compiled with the Intel Fortran Compiler 19.0.1.144.

I hope the information provided is sufficient and i have not made any gross mistakes. thanks in advance for your help!

Erik

**Comment by hfp** [comment] 2020-08-17 08:31
Erik, thank you for your report and for talking back!

I will of course try scaling to multiple sockets even on Haswell server (since this is the reported arch reproducing the problem). Anyhow, I noticed a problem in above code which might be just because of providing an excerpt rather than the full picture...

Suppose the above snippets are in a parallel region, dispatching the code works without data race in any of the cases (`omp single`). However, `libxsmm_available` can return `.FALSE.` for some of the threads while one of the threads ("single") just dispatches the code. This might be unintentionally without "fallback" (since there is no `ELSE` condition). LIBXSMM adjusted policy of when code is "available", which means `libxsmm_available` is *almost* useless as we guarantee `libxsmm_dispatch` to succeed and produce code (unless an unsupported case was requested). We currently limit Alpha, Beta, and TransA to 1, { 1, 0 }, and 'N' respectively (which also means TransB = {'N','T'} is supported). However, your code is constructed such that `libxsmm_available` is still necessary (one thread dispatches, others may rely on the result of that thread *before* work is completed).

There are two alternatives (beside of introducing a fallback).

1. Perform `libxsmm_dispatch` outside of the parallel region, i.e., prior to opening the region. This might be unsuitable due to modularization (running LIBXSMM really is deeply nested in a routine called in a parallel region.
2. Use below code.

```fortran
TYPE(LIBXSMM_DMMFUNCTION) :: xmm ! no save attribute to avoid data race
CALL libxsmm_dispatch(xmm, m, n, k) ! code is contended among threads
!$omp do
DO i = LBOUND(c, 3), UBOUND(c, 3)
  CALL libxsmm_dmmcall(xmm, a(:,:,i), b(:,:,i), c(:,:,i))
END DO
```

Routine `libxsmm_dispatch` is synchronized internally and it is save for multiple threads to call the routine concurrently. The contention should be no concern since the DO-loop below easily amortizes the dispatch as well as the contention.

**Comment by ErikP94** [comment] 2020-08-19 08:11
Hello Mr Pabst!

Many thanks for your reply!

As you yourself have already indicated, alternative 1 is unfortunately not suitable for our application.
But thanks for the hint with the libxsmm_available, I have removed it from the code.
Unfortunately, apart from that, we have already examined a variant that is like alternative 2. The scaling problem still existed.

It almost acts as if there was an upper limit to the achievable performance. I don't have these scaling problems for other (e.g. smaller) matrix sizes, with which I achieve a lower performance already for one Thread.

Thank you for your help and for addressing the problem!

Best, 
Erik

**Comment by hfp** [comment] 2020-08-19 14:35
I will create a proxy-code which is trying to reproduce the problem. I will play with different loop schedules and pinning schemes (OpenMP), and report scalability from 1st to 2nd socket for different hardware platforms including Haswell server. Ideally we would see 2x going from one to two sockets even if the code is memory-bound (because of harvesting/doubling the number of memory controllers when approaching the second socket). I will let you know!

Regarding the first-touch principle, I will both try with "ideal" initialization as well as single-core based data-setup. For the latter, I will also try interleaved pages (`numactl -i all`).

**Comment by ErikP94** [comment] 2020-08-19 16:00
Thank you alot!

Another information that might be useful for you: the values for m,n,k are 16.

**Comment by hfp** [comment] 2020-08-24 07:27
Hello Erik, thank you for the details!

I have [extended](https://github.com/hfp/libxsmm/blob/master/samples/smm/smm.f#L213-L223) the Fortran SMM sample code, and hopefully got it close enough to your case. Feel free to privately modify if necessary (or send a Pull Request if you want to keep your reproduces alive). I did the following experiment(s):

```bash
make -j
cd samples/smm; make -j
export OMP_PROC_BIND=CLOSE
./smm 16
```

Please use `smm` rather than `smm.sh` to control affinity on your own for this specific experiment (`OMP_PROC_BIND` works for both Intel and GNU compiler). Running above experiment with `OMP_NUM_THREADS` at half the number of total HW threads, I get a speedup of above or equal 1.9x by using the second socket on either Skylake server (specifically Cascade Lake) or Haswell server (specifically Broadwell). Either Intel Compiler or GNU Fortran (respective OpenMP runtime) reproduce the same behavior (alternatively, `numactl` or `taskset` can be used for the experiment as well). Given a scalability of more or equal to 1.9x, I cannot reproduce the problem. For this experiment `a` and `b` are likely initialized with the same affinity (hence no NUMA issue from that side) and `c` is kept uninitialized assuming `Beta=0` (and hence no NUMA issue from this side). If your code uses `Beta=1` to accumulate into `c`, please let me know!

Beside of the above experiment, I added some new capability to the Fortran interface: `LIBXSMM_GEMM_FLAG_ALIGN_C_NTS_HINT_BETA_0`, i.e., support for Non-Temporal Stores (NTS). The latter goes along with `Beta=0` and the requirement for (SIMD-)aligned accesses (`c` array). The new function `libxsmm_aligned` tells whether an array and subsequent accesses are aligned. For general code, NTS only makes sense if `c` is somewhat large (does not fit into cache) and is not touched immediately after running the LIBXSMM kernel (otherwise it is beneficial to keep `c` "on record", i.e., in-cache (NTS writes through and may not keep the data in cache). Note, NTS requires aligned accesses but not all Fortran compilers easily (or sufficiently) align the allocated memory (Intel Compiler supports some [attribute](https://github.com/hfp/libxsmm/blob/master/samples/smm/smm.f#L22)). If you experience some erratic timing during your experiments ("instable"), I believe it can be related to

```fortran
        DO r = 1, repetitions
          !$OMP PARALLEL DEFAULT(NONE) SHARED(a, b, c)
          CALL smm_stream_abc(a, b, c)
          !$OMP END PARALLEL
        END DO
```

... which does not look ideal (since the parallel region is opened/joined within a loop). However, in your application you likely have more code inside the parallel region plus you may not repeat with such loop (it is only there for the sake of stable timing ;-).

Generally, your case (M,N,K=16) is memory-bound with above mentioned systems since all operands are streamed (`a`, `b`, and `c`). Further, NTS may not help too much: theoretically in the order of 25% (I measured ~15%) since the code reads `a`, `b`, and two times `c` (RFO) vs `a`, `b`, and one times `c` (NTS) which is "4 : 3" for NTS vs Read-For-Ownership (RFO).

**Comment by hfp** [comment] 2020-08-24 07:38
If your case cannot easily initialize memory in a NUMA aware fashion, I suggest to try `numactl -i all` in front of your command. The latter interleaves all memory pages across both sockets (which does not get you all the bandwidth but perhaps somewhat better than populating all pages on socket-0).

**Comment by ErikP94** [comment] 2020-08-25 13:29
Dear Mr Pabst,

I am sorry that I did not send you this information earlier: in our code, we indeed use `Beta=1` to accumulate `c`.
I will think of an alternative formulation for `Beta=0` and possibly try some things mentioned above. 
Thanks until here!

**Comment by hfp** [comment] 2020-08-25 13:38
No worries regarding the `Beta=0`, I wanted NTS to be supported in Fortran code anyway. I will add/try a case with `Beta=1` just to make sure, but I believe it will scale similar to the currently implemented case. The only reason not to scale might be if `c` (where the writes go into) are not split at cacheline boundaries among threads (`OMP DO`). If the latter is true ("false sharing"), it can be fixed by giving some granularity to the OMP-DO-directive.

**Comment by hfp** [comment] 2020-08-26 10:58
Just FYI, LIBXSMM/master now by default implements intercepting memory allocations in a very light-weight fashion with just the purpose of aligning buffers sufficiently. This has some different goal/purpose than building [LIBXSMM_MALLOC=-1](https://libxsmm.readthedocs.io/libxsmm_tune/#intercepted-allocations) (or LIBXSMM_MALLOC=1), which may take longer on a per-allocation basis but can potentially amortize multiple allocations that are in the same place. It is not yet decided if this "light-weight interception" can stay enabled by default. However, GNU Fortran can now close the gap with IFORT by also delivering aligned memory (always and without an attribute). In turn, this helps with NTS for the case with Beta=0 when relying on GNU Fortran.

**Comment by ErikP94** [comment] 2020-08-28 07:33
Thank you for your help!

**Comment by hfp** [comment] 2020-09-02 14:44
Thank you for your contribution!

( Of course, feel free to reopen the issue or to open a new issue depending on your findings. )

**Closed by hfp** 2020-09-02 14:44 UTC
Labels: question
