### ISSUE TITLE
Implement dynamic code dispatch for ISA extensions

### ISSUE THREAD

**Issue by hfp** [hfp/libxsmm#27] opened 2015-10-29 16:42 UTC
Currently a single code path (instruction set extension) is supported and determined at build time of the library. This is true for the statically requested kernels but also for the JITted code, both of which can support selecting the architecture at runtime (initialization time of the library). To actually implement this feature, we can check feature bits our self, or rely on certain attributes available for both the Intel and the GNU based tool chain. The solution based on attributes might preferred with respect to maintenance. However, the level of ISA-dispatch will be ultimately driven by an anticipated performance impact (we do not want a performance impact due to supporting this feature). Fixing this issue is to at least enable JITted code matching the platform at runtime.

**Comment by alheinecke** [comment] 2015-10-29 16:46
Duplicate of issue #24

**Closed** 2015-10-29 16:47 UTC
Labels: duplicate
