### ISSUE TITLE
1.11: .pc file contains the staging directory

### ISSUE THREAD

**Issue by yurivict** [hfp/libxsmm#334] opened 2019-05-03 03:58 UTC
```
====> Running Q/A tests (stage-qa)
Error: 'lib/libxsmmnoblas.pc' is referring to /usr/ports/math/libxsmm/work/stage
Error: 'lib/libxsmmext.pc' is referring to /usr/ports/math/libxsmm/work/stage
Error: 'lib/libxsmmf.pc' is referring to /usr/ports/math/libxsmm/work/stage
Error: 'lib/libxsmm.pc' is referring to /usr/ports/math/libxsmm/work/stage
*** Error code 1
```

Contents of the .pc file:
```
Name: libxsmm/noblas
Description: LIBXSMM substituted LAPACK/BLAS dependency
URL: https://github.com/hfp/libxsmm
Version: 1.11.0

prefix=/usr/ports/math/libxsmm/work/stage/usr/local
includedir=include
libdir=lib

Requires: libxsmm
Cflags: -I${includedir}
Libs: -L${libdir} -lxsmmnoblas
```

Additionally, .pc file is misplaced, ```/usr/local/lib/libxsmmnoblas.pc``` is a wrong location. The normal location is ```libdata/pkgconfig/```.

**Comment by hfp** [comment] 2019-05-03 06:01
Thank you for the reproducer! I will release a fixed version shortly.

**Comment by hfp** [comment] 2019-05-03 06:02
This is at least related to issue #333.

**Comment by hfp** [comment] 2019-05-03 11:42
Can you let me know the (make-)command (or whatever) which produced the incorrect result or can you check again with the current master?  Though, I fixed one case but the one you reported looks different.

**Comment by hfp** [comment] 2019-05-03 11:45
I think what you want is the pkg-file's prefix set to PREFIX/DESTDIR even when not running `make install`.

**Comment by hfp** [comment] 2019-05-09 09:14
This is now hopefully fixed and targeted for v1.12. There is an updated documentation [here](https://libxsmm.readthedocs.io/#install-destdir) for DESTDIR, PREFIX, and DESTDIR vs. PREFIX. In addition, I have implemented PPKGDIR to set the location of the `.pc` files relative to the DESTDIR/PREFIX. For FreeBSD, PPKGDIR defaults to `libdata/pkgconfig` otherwise it defaults to `lib` as it was/is.

**Comment by yurivict** [comment] 2019-05-20 07:22
1.12 still has this problem. (!!!)

**Comment by hfp** [comment] 2019-05-20 07:25
Thank you for your report! Can you please let me know the command to generate the package plus the location of the repo containing the maintainer stuff?

**Comment by yurivict** [comment] 2019-05-20 07:31
This is the FreeBSD port.

If you don't have FreeBSD, you can for example install this VirtualBox applicance https://people.freebsd.org/~yuri/FreeBSD-12-amd64.ova, boot it with login=root password=root.

Then:
1. ```cd /usr/ports/math/libxsmm```
2. ```pkg install -A $(make missing)```
3. In ```Makefile``` change ```DISTVERSION``` to ```1.12```
4. ```make makesum build```
5. Observe it complaining about .pc file.

**Comment by hfp** [comment] 2019-05-20 08:35
Of course, I have a test image of FreeBSD 12 already. However, I wanted to try your image because of the ready-to-use environment. However, I am getting "VBoxManage: error: VMDK: Compressed image is corrupted" (I redownloaded but apparently there is some issue).

I think it would be sufficient to get the content of `/usr/ports/math/libxsmm`. Is this the checked-out maintainer repo and where can I clone it from? Apprently `make missing` is nothing understood by the original Makefile.

**Comment by yurivict** [comment] 2019-05-20 08:48
This isn't VMDK, it is an appliance and it needs to be imported using "Import Apliance" menu item.
I tried it before and it worked.

-------

Anyways, this is a standard FreeBSD port. The ports tree can be checked out using:
> svn checkout https://svn.FreeBSD.org/ports/head /usr/ports

**Comment by hfp** [comment] 2019-05-23 08:41
The fix is due today (v1.12.1). Under FreeBSD, a maintainer build is [detected](https://github.com/hfp/libxsmm/blob/master/Makefile#L1578) and the PREFIX is automatically set to `/usr/local` plus the subdirectory for dropping the `.pc` files is preset as well (`libdata/pkgconfig`). 

I found that the package builder (`pkg`) does not set `DESTDIR` and even if it is set in the Makefile of the port, it is forceable overridden to remain empty. However, in the afore mentioned Makefile the `PREFIX` key works (if something different than `/usr/local` is needed).

The [documentation](https://libxsmm.readthedocs.io/#install-destdir) regarding `DESTDIR` and `PREFIX` was updated once more, and both key are now treated equal plus some complicated flow was dropped which previously considered whether `make install` is invoked or not. Both keys are supported because for instance APT package builder can make use of `DESTDIR` producing a package that is correct out of the box.

**Comment by yurivict** [comment] 2019-07-22 04:54
.pc files still contain the build directory.

Also, https://github.com/hfp/libxsmm/blob/master/Makefile#L1558 hardcodes ```/usr/local```. It should be using ```$(prefix)```.

1.13-7-g4c3a6925e

**Comment by yurivict** [comment] 2019-08-25 19:36
This isn't resolved: https://github.com/hfp/libxsmm/issues/347
38ada493a still has this problem.

**Comment by yurivict** [comment] 2020-01-12 08:34
This is still not fixed:
```
====> Running Q/A tests (stage-qa)
Error: '/wrkdirs/usr/ports/math/libxsmm/work/stage/lib/libxsmmnoblas.pc' is referring to /wrkdirs/usr/ports/math/libxsmm/work/stage
Error: '/wrkdirs/usr/ports/math/libxsmm/work/stage/lib/module' is referring to /wrkdirs/usr/ports/math/libxsmm/work/stage
Error: '/wrkdirs/usr/ports/math/libxsmm/work/stage/lib/libxsmmf.pc' is referring to /wrkdirs/usr/ports/math/libxsmm/work/stage
Error: '/wrkdirs/usr/ports/math/libxsmm/work/stage/lib/libxsmm.pc' is referring to /wrkdirs/usr/ports/math/libxsmm/work/stage
Error: '/wrkdirs/usr/ports/math/libxsmm/work/stage/lib/libxsmmext.pc' is referring to /wrkdirs/usr/ports/math/libxsmm/work/stage
```

**Comment by hfp** [comment] 2020-01-29 07:24
See #347

**Comment by yurivict** [comment] 2020-01-29 07:42
This is very easy to test indeed. Just install it into a stage directory $DESTDIR and then grep in the installation for its own directory name. It should never be found there.

**Comment by hfp** [comment] 2020-01-29 07:45
Thanks for the details, it's indeed important to reproduce the issue (and finally fix it)!

**Comment by hfp** [comment] 2020-02-26 14:06
This issue is (finally) fixed. I have validated all relevant pkg-stages (including the successfully generated package). Note: the Makefile-patch as present in the ports-repository does not apply anymore (and can be removed). Also, the pkg-plist target may be used to update the list of files (plist). For convenience, all binaries are now stripped (as recommended when building a package).

**Closed** 2020-03-06 08:50 UTC
Labels: duplicate
