### ISSUE TITLE
Installs files into the root directory / instread of into $PREFIX

### ISSUE THREAD

**Issue by yurivict** [hfp/libxsmm#371] opened 2020-03-06 09:03 UTC
```
====> Running Q/A tests (stage-qa)
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: /bin/libxsmm_gemm_generator
Error: Orphaned: /include/libxsmm.f
Error: Orphaned: /include/libxsmm.h
Error: Orphaned: /include/libxsmm.mod
Error: Orphaned: /include/libxsmm/generator_common.c
Error: Orphaned: /include/libxsmm/generator_common.h
Error: Orphaned: /include/libxsmm/generator_gemm.c
...
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: bin/libxsmm_conv_generator
Error: Missing: bin/libxsmm_convwino_generator
Error: Missing: bin/libxsmm_gemm_generator
Error: Missing: include/libxsmm.f
Error: Missing: include/libxsmm.h
Error: Missing: include/libxsmm.mod
Error: Missing: include/libxsmm/generator_common.c
Error: Missing: include/libxsmm/generator_common.h
...
```

FreeBSD 12

**Comment by hfp** [comment] 2020-03-07 19:48
You need to update the pkg-plist. It even contains items that are removed from the library. To summarize [this comment](https://github.com/hfp/libxsmm/issues/334#issuecomment-591442731):

* The Makefile-patch as present in the ports-repository does not apply anymore (and can be removed)
* The plist is outdated and may be regenerated per `make makeplist`. Doing so kindly asks to double-check the generated file. In fact, it is not so kind, it adds a dummy-entry at the top which must be removed.

For the plist business, I found [this](https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/plist-dynamic.html) reference useful.

**Comment by yurivict** [comment] 2020-03-07 19:50
The problem is that the items in STAGEDIR are in the invalid location: ex. ```/bin/libxsmm_gemm_generator```. They can't be installed into the root.

**Comment by hfp** [comment] 2020-03-08 15:27
I will try reproducing this. I had everything to the point of creating the package without any hacks or adjustments. Let me re-check...

**Comment by hfp** [comment] 2020-03-08 15:29
What was motivating my ealier comment was `Error: Missing: bin/libxsmm_conv_generator` and 
`Error: Missing: bin/libxsmm_convwino_generator`, which are both removed from LIBXSMM. I wonder how a wrong plist affected the other issue. Anyhow, I will look into this once more.

**Comment by yurivict** [comment] 2020-03-08 15:41
> I wonder how a wrong plist affected the other issue.

These are missing from the stage directory because they were in the old plist but were removed by the project.

**Comment by hfp** [comment] 2020-03-08 17:58
It works completely flawless for me (no warnings or issue up to the fresh ready-to-install package). I am doing the following:

```bash
cd /usr/ports
svn update
cd /usr/ports/math/libxsmm
rm files/patch-Makefile
vi Makefile
```

I am editing the Makefile for the following entries (today's revision of LIBXSMM):

```Make
  DISTVERSION=    g20200308
  GH_TAGNAME=     92b14bf
```

I am then continuing with building the package:

```bash
make clean
make makesum
make build
make stage
make stage-qa
make package
make install
```

The plist is regenerated like:

```bash
make makeplist > pkg-plist
vi pkg-plist
```

I am deleting the first line (`/you/have/to/check/what/makeplist/gives/you`).

**Comment by yurivict** [comment] 2020-03-08 18:11
The problem is gone in the current master.

Thanks for letting me know!

**Comment by hfp** [comment] 2020-03-08 18:26
Thanks!  The fix will land in v1.15 to be released asap.

( Sorry, I should have said that LIBXSMM from 2020/02/26 is the fixed revision. Since then, every revision should work, hopefully going forward this way. )

Thank you again for your patience!

**Comment by yurivict** [comment] 2020-03-08 18:35
Thank you for fixing it!

**Comment by yurivict** [comment] 2020-03-08 19:48
Now I found that the problem is still there. It installs the files properly when built locally, but installs them into / when built in poudriere.

**Comment by yurivict** [comment] 2020-03-08 19:53
Installation should be done into ```$(DESTDIR)$(PREFIX)```.

You have
```
ifneq (,$(strip $(DESTDIR)))
  override PREFIX = $(DESTDIR)
endif
```

and then just install into ```$(PREFIX)``` ignoring the real ```PREFIX```.

I think that's what's causing this issue.

**Comment by hfp** [comment] 2020-03-10 08:26
The issue is resolved:

```text
  DISTVERSION=    g20200309
  GH_TAGNAME=     d5c67f8
```

Note: the issue took longer (#334, #347, and finally #371) to resolve since the install stage was/is specified slightly different than expected by FreeBSD packaging tools. We have, install-here, install-prefix, out-of-tree build, and combinations of the former. Hence, it took some iterations to meet all expectations and not breaking an existing flow.

**Comment by hfp** [comment] 2020-03-10 08:31
I could not test with Poudriere but the resolution is now not attempting to detect the "maintainer situation", i.e., if it works once (pkg flow) it works everywhere the same way. ( Btw, Poudriere ran into an issue when building GCC 9.2 just before reaching the point of building libxsmm. )

**Comment by hfp** [comment] 2020-03-11 19:46
Version 1.15 will be released Friday 13th if this issue is resolved.

**Closed by hfp** 2020-03-11 19:46 UTC
