### ISSUE TITLE
Performance for Nek reproducer is broken

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#64] opened 2016-02-17 18:50 UTC
with latest master:

make realclean
make
cd sample/nek/
make realclean
make 
[XYZ nek]$ export KMP_AFFINITY=proclist=[0-17],granularity=thread,explicit,verbose
[XYZ nek]$ export OMP_NUM_THREADS=18
[XYZ nek]$ ./axhm 8 8 8 1000 7000000
[...]
OMP: Info #242: KMP_AFFINITY: pid 117274 thread 0 bound to OS proc set {0}
OMP: Info #242: KMP_AFFINITY: pid 117274 thread 1 bound to OS proc set {1}
OMP: Info #242: KMP_AFFINITY: pid 117274 thread 2 bound to OS proc set {2}
OMP: Info #242: KMP_AFFINITY: pid 117274 thread 3 bound to OS proc set {3}
OMP: Info #242: KMP_AFFINITY: pid 117274 thread 4 bound to OS proc set {4}
OMP: Info #242: KMP_AFFINITY: pid 117274 thread 6 bound to OS proc set {6}
OMP: Info #242: KMP_AFFINITY: pid 117274 thread 7 bound to OS proc set {7}
OMP: Info #242: KMP_AFFINITY: pid 117274 thread 5 bound to OS proc set {5}
OMP: Info #242: KMP_AFFINITY: pid 117274 thread 8 bound to OS proc set {8}
OMP: Info #242: KMP_AFFINITY: pid 117274 thread 9 bound to OS proc set {9}
OMP: Info #242: KMP_AFFINITY: pid 117274 thread 10 bound to OS proc set {10}
OMP: Info #242: KMP_AFFINITY: pid 117274 thread 11 bound to OS proc set {11}
OMP: Info #242: KMP_AFFINITY: pid 117274 thread 12 bound to OS proc set {12}
OMP: Info #242: KMP_AFFINITY: pid 117274 thread 13 bound to OS proc set {13}
OMP: Info #242: KMP_AFFINITY: pid 117274 thread 14 bound to OS proc set {14}
OMP: Info #242: KMP_AFFINITY: pid 117274 thread 15 bound to OS proc set {15}
OMP: Info #242: KMP_AFFINITY: pid 117274 thread 16 bound to OS proc set {16}
OMP: Info #242: KMP_AFFINITY: pid 117274 thread 17 bound to OS proc set {17}
m=8 n=8 k=8 size=1000 reps=7000
Streamed... (BLAS)
	performance:     104.9 GFLOPS/s
	bandwidth:        86.9 GB/s
	duration:          0.3 ms
Streamed... (mxm)
	performance:     135.6 GFLOPS/s
	bandwidth:       112.3 GB/s
	duration:          0.2 ms
Streamed... (auto-dispatched)
	performance:     128.5 GFLOPS/s
	bandwidth:       106.3 GB/s
	duration:          0.2 ms
Streamed... (specialized)
	performance:      53.7 GFLOPS/s
	bandwidth:        44.5 GB/s
	duration:          0.5 ms

These numbers do not make sense, one socket has just 59 GB/s stream bandwidth.

The part is a Intel Xeon E5-2699v3, COD enabled.

=====  Placement on packages  =====
Package Id.	Core Id.	Processors
0   		0,1,2,3,4,8,9,10,11,16,17,18,19,20,24,25,26,27		(0,36)(1,37)(2,38)(3,39)(4,40)(5,41)(6,42)(7,43)(8,44)(9,45)(10,46)(11,47)(12,48)(13,49)(14,50)(15,51)(16,52)(17,53)
1   		0,1,2,3,4,8,9,10,11,16,17,18,19,20,24,25,26,27		(18,54)(19,55)(20,56)(21,57)(22,58)(23,59)(24,60)(25,61)(26,62)(27,63)(28,64)(29,65)(30,66)(31,67)(32,68)(33,69)(34,70)(35,71)

=====  Cache sharing  =====
Cache	Size		Processors
L1	32  KB		(0,36)(1,37)(2,38)(3,39)(4,40)(5,41)(6,42)(7,43)(8,44)(9,45)(10,46)(11,47)(12,48)(13,49)(14,50)(15,51)(16,52)(17,53)(18,54)(19,55)(20,56)(21,57)(22,58)(23,59)(24,60)(25,61)(26,62)(27,63)(28,64)(29,65)(30,66)(31,67)(32,68)(33,69)(34,70)(35,71)
L2	256 KB		(0,36)(1,37)(2,38)(3,39)(4,40)(5,41)(6,42)(7,43)(8,44)(9,45)(10,46)(11,47)(12,48)(13,49)(14,50)(15,51)(16,52)(17,53)(18,54)(19,55)(20,56)(21,57)(22,58)(23,59)(24,60)(25,61)(26,62)(27,63)(28,64)(29,65)(30,66)(31,67)(32,68)(33,69)(34,70)(35,71)
L3	22  MB		(0,1,2,3,4,5,6,7,8,36,37,38,39,40,41,42,43,44)(9,10,11,12,13,14,15,16,17,45,46,47,48,49,50,51,52,53)(18,19,20,21,22,23,24,25,26,54,55,56,57,58,59,60,61,62)(27,28,29,30,31,32,33,34,35,63,64,65,66,67,68,69,70,71)

**Comment by hfp** [comment] 2016-02-18 10:30
This is fixed in the master revision. The problem was unveiled/introduced at the time where the repetition got introduced (the repetition-loop is part of a parallel region and thus participates in the work share which increased parallelism and also the chance that the master thread [which is measuring the duration] finished earlier than other workers). The actual origin of the problem is about missing barriers to ensure all work is finished up before measuring the total duration needed.

However, there is an issue unveiled now that the NEK samples are supposed to measure correct numbers: there is a performance issue/regression with directly calling a pre-dispatched kernel ("specialized"). Investigating...

**Closed** 2016-02-18 13:52 UTC
Labels: bug
