### ISSUE TITLE
Provide a pkg-config file or similar to help with static linking

### ISSUE THREAD

**Issue by dev-zero** [hfp/libxsmm#269] opened 2018-10-17 23:19 UTC
It seems that - depending on compiler and platform - several additional linker flags have to be passed when linking libxsmm statically, see for example:

* https://github.com/spack/spack/pull/9308/commits/5b0042050a5bed02643361c1ae27708b69b0d01d
* https://github.com/spack/spack/pull/9308#issuecomment-430815341

Other projects provide either a `.pc` pkg-config (preferred) or libtool `.la` files to help with that but I guess any other method where we could easily retrieve the required flags would help.

**Comment by dev-zero** [comment] 2018-10-22 07:54
Nice, thank you very much! Do you have a rough ETA for v1.10?

**Comment by dev-zero** [comment] 2018-10-22 07:54
Nice, thank you very much! Do you have a rough ETA for v1.10?

**Comment by hfp** [comment] 2018-10-22 08:16
This week at best and by end of this month in any case.

**Comment by dev-zero** [comment] 2018-10-22 15:08
@hfp awesome, thanks!

**Comment by dev-zero** [comment] 2018-10-22 15:34
the current 2fb520d295f2cab5646f69f0e90e477037b71a12 `.pc`-generation seems to have a problem:

```
Name: libxsmm
Description: Matrix operations and deep learning primitives
URL: https://github.com/hfp/libxsmm
Version: 1.9.0

prefix=/scratch/tiziano/work/libxsmm
includedir=${prefix}/include
libdir=${prefix}/lib

Cflags: -I${includedir}
Libs: -L${libdir} -lxsmm
Libs.private: -lpthread -lrt
 -ldl -lm -lc
```
... there's a newline before the `-ldl ...`, making `pkg-config` ignore those libraries:

```console
$ PKG_CONFIG_PATH="$PWD/lib" pkg-config --libs --static libxsmm
-L/scratch/tiziano/work/libxsmm/lib -lxsmm -lpthread -lrt
```

**Comment by hfp** [comment] 2018-10-22 16:41
The ETA is by the end of this week at best and by the end of this month in any case.

**Comment by hfp** [comment] 2018-10-22 19:39
Thanks for testing the pc-file(s). The issue is now fixed.

**Closed** 2018-10-23 18:32 UTC
Labels: enhancement
