### ISSUE TITLE
memory leak when calling LIBXSMM_XBLAS_SYMBOL(float)(...)

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#291] opened 2018-12-02 01:11 UTC
When running the lstmdriver with the following settings:

export OMP_NUM_THREADS=1
export LIBXSMM_TARGET=snb or hsw
export LIBXSMM_VERBOSE=-1
 
and compiling the lstmdriver with "make realclean && make OMP=0"

CHECK=1 valgrind ./lstmdriver 1 3 64 64 64 4

Memory leaks from 5 allocations are reported. These are not there when running

valgrind ./lstmdriver 1 3 64 64 64 4

They have been root-caused: They are due to the LIBXSMM_XBLAS_SYMBOL(float)(...) calls. If all of these calls are commented, also the "CHECK=1" runs without memory leaks.

**Comment by hfp** [comment] 2019-01-02 15:10
Thanks for reporting the issue! The problem is fixed in LIBXSMM/master, in particular today's commits are related to the problem.

**Closed by hfp** 2019-01-02 15:10 UTC
