### ISSUE TITLE
-cp2k flag in make.sh

### ISSUE THREAD

**Issue by joanwa** [hfp/libxsmm#59] opened 2016-01-18 15:29 UTC
hey all,
just a few quick questions about the -cp2k flag in make.sh. Is it supposed to deliver a cp2k suitable library?

I see that the MNK options are  

MNK=" \
    23, \
    6, \
    14 16 29, \
    14 32 29, \
    5 32 13 24 26, \
    9 32 22, \
    64, \
    78, \
    16 29 55, \
    32 29 55, \
    12, \
    4 5 7 9 13 25 26 28 32 45"

But in the cp2k's toolchain installer the MNK options are 

MNK="1 4 5 6 8 9 13 16 17 22 23 24 26 32"
which are many less, but also different combinations. 

Next it sets SSE=3, which according to the makefile.inc and documentation doesn't exist. Only SSE=1 and AVX=1|2|3 exists. 

And last, I read Intel optimized and the cp2k.pdf inside documentation says I should have icc. Is it also supposed to work with gcc compiler? I did manage to compile it with gcc. Are there any issues with gcc?

Thank you for any answers.

Johannes

**Comment by hfp** [comment] 2016-01-18 16:01
Hello Johannes,

thank your sending your questions!

The MNK options in the make.sh are adopted from https://github.com/cp2k/cp2k/blob/master/cp2k/src/dbcsr/libsmm_acc/libcusmm/generate.py#L19. However, this (or any other statically generated set of kernels) is perhaps not able to "catch them all" but rather aims for being "sufficient for most use cases".

For LIBXSMM, the actual collection of statically generated kernels only matters for systems with no AVX capability (SSE only). This is because the JIT technology is not covering non-AVX (i.e. SSE) when generating a kernel at runtime. I took some effort to support a "general" library which can be deployed to an unknown system environment, see: https://github.com/hfp/libxsmm/#installation.

Please note that the CP2K toolchain installer will be revised pretty soon and then cover the upcoming LIBXSMM 1.2. By then, some of the (now) superfluous flags when building the library can/should be removed.

**Comment by hfp** [comment] 2016-01-18 16:06
>>> Next it sets SSE=3, which according to the makefile.inc and documentation doesn't exist.
>>> Only SSE=1 and AVX=1|2|3 exists.

Yes, and the reason is I did not want to give the choice of the kind of SSE level (SSE2, SSE3, SSSE3, SSE4.1, SSE4.2) because the CRC32 calculation requires SSE 4.2. In an earlier version, there was a choice for SSE=x, however it disabled accelerated CRC32 calculations used by the auto-dispatch. Anyhow, I could actually reintroduce this choice because since last week I have implemented CPUID-based dispatch of the code path using the CRC32 instructions. Therefore compiling with whatever SSE support is not affecting the availability of the accelerated CRC32 instructions.

**Comment by hfp** [comment] 2016-01-18 16:18
> And last, I read Intel optimized and the cp2k.pdf inside documentation says I should have icc.
This is only talking about the CP2K/intel branch. Since CP2K 3.0, LIBXSMM can be used without the code in the Intel branch. However, the CP2K/intel branch remains available and is also using the Intel Software Development tools (compiler) along with some specific ARCH files. This is because, other optimizations might be developed there without interfering with the CP2K development.

> Is it also supposed to work with gcc compiler?
Yes, just take the CP2K 3.0 release package for production needs, or the CP2K/master from Git, or CP2K/trunk from SourceForge if you need anything beyond production/released code.

> I did manage to compile it with gcc. Are there any issues with gcc?
Absolutely not! Please go ahead and use GCC. Also, LIBXSMM is not depending on compiler optimizations in order to deliver good performance. Our JIT code generator is not affected by the actual compiler used, and also when generating static source code/kernels (non-JIT) it uses inline assembly and therefore is again not affected by compiler optimizations.

**Comment by hfp** [comment] 2016-01-18 16:42
Last but not least, LIBXSMM 1.2 is in preparation and CP2K-wise only issue #58 is pending/incomplete.

**Comment by joanwa** [comment] 2016-01-18 17:09
thanks for all the prompt answers. Almost everything to satisfaction answered :) one remaining issue is gcc compilation. It does compile, however produces f77 warnings upfront (gcc/gfortran 5.3.1):

make AVX=2
f77  -fPIC -ffree-form -O2 -ftree-vectorize -ffast-math -funroll-loops   -D__extern_always_inline=inline -DNDEBUG -D__STATIC -Iinclude -Ibuild -I/home/wagnerjs/programs/source/build/libxsmm-1.1.1/src -mavx2 -c include/libxsmm.f -o build/libxsmm-mod.o -J include/
f77: unrecognized option `-J'
f77: include/: linker input file unused because linking not done
f771: error: invalid option `avx2'
f771: error: unrecognized command line option "-ftree-vectorize"
Makefile:266: recipe for target 'include/libxsmm.f' failed
make: *** [include/libxsmm.f] Error 1

upon 2nd run it goes ahead and creates cc compiled code. Is that a known issue?

**Comment by hfp** [comment] 2016-01-19 07:48
This problem is related to issue #58, and it will be fixed today. If you cannot wait (but still want the latest), you can do the following (beside of getting the last release):
$ git clone https://github.com/hfp/libxsmm.git ; cd libxsmm
$ git reset --hard f27d830

**Comment by hfp** [comment] 2016-01-19 09:23
> make AVX=2
> f77 -fPIC -ffree-form -O2 -ftree-vectorize -ffast-math -funroll-loops -D__extern_always_inline=inline -DNDEBUG -D__STATIC -Iinclude -Ibuild -I/home/wagnerjs/programs/source/build/libxsmm-1.1.1/src -mavx2 -c include/libxsmm.f -o build/libxsmm-mod.o -J include/
> f77: unrecognized option -J' f77: include/: linker input file unused because linking not done f771: error: invalid optionavx2'
> f771: error: unrecognized command line option "-ftree-vectorize"
> Makefile:266: recipe for target 'include/libxsmm.f' failed
> make: *** [include/libxsmm.f] Error 1

This looks like an extremely outdated GNU Fortran compiler version (version 3.x?). It appears this is not only caused by implying Fortran 77 compatibility ("f77") but also due to AVX2 being unknown (-mavx2). Please note, LIBXSMM's Fortran requirement is the Fortran 2003 standard. There is currently no support for those who want F77. In your case, this aforementioned "f77" compiler should also cause problems with building CP2K. If this was not the case, it somehow caused LIBXSMM to rely on the f77 compiler. By default the Makefile uses the "FC" variable, if this picks "f77" in your case I will revise relying on `FC` (Makefile), and perhaps fix it up to check for gfortran.

I think the following will help with the reported issue:
```
make CXX=g++ CC=gcc FC=gfortran AVX=2
```

**Comment by hfp** [comment] 2016-01-20 12:46
As of commit 5e8e152 (current master), there have been a number of improvements made of the build system. For example, the aforementioned "f77" issue should now be covered by appropriate warning message when building LIBXSMM.

**Closed by hfp** 2016-01-20 12:46 UTC
Labels: question

**Comment by joanwa** [comment] 2016-01-20 13:16
yes is solved on linux. Building on OS X however is different result. Using the system compilers (Apple LLVM version 7.0.2 (clang-700.1.81))

gives at first a similar fortran linking error:

sed: 1: "include/libxsmm.f": command i expects \ followed by text
make: *** [include/libxsmm.f] Error 1

and upon 2nd run it does compile. But using gnu compilers on OS X (gcc-5 (Homebrew gcc 5.3.0) 5.3.0) gives the former plus this in the middle:

gcc-5  -Wall -Wno-unused-function -Wno-attributes -fPIC -O2 -ftree-vectorize -ffast-math -funroll-loops   -D__extern_always_inline=inline -DNDEBUG -D__STATIC -Iinclude -Ibuild -I/Users/install/libxsmm-1.1.1/src -msse4.2 -c /Users/install/libxsmm-1.1.1/src/libxsmm_dispatch.c -o build/intel64/libxsmm_dispatch.o
/Users/install/libxsmm-1.1.1/src/libxsmm_dispatch.c: In function 'internal_build':
/Users/install/libxsmm-1.1.1/src/libxsmm_dispatch.c:334:7: note: #pragma message: ====================================================================
       LIBXSMM_MESSAGE("====================================================================")
       ^
/Users/install/libxsmm-1.1.1/src/libxsmm_dispatch.c:335:7: note: #pragma message: Adjusting THP is unavailable due to C89 or kernel older than 2.6.38!
       LIBXSMM_MESSAGE("Adjusting THP is unavailable due to C89 or kernel older than 2.6.38!")
       ^
/Users/install/libxsmm-1.1.1/src/libxsmm_dispatch.c:336:7: note: #pragma message: ====================================================================
       LIBXSMM_MESSAGE("====================================================================")
       ^

**Comment by joanwa** [comment] 2016-01-20 13:24
right, indeed I didn't set FC on linux. On OS X it automatically picket gfortran, on linux it defaultet to f77 insteast of gfortran 5.3

**Comment by hfp** [comment] 2016-01-20 13:28
Well, test coverage on OS X is currently weak. In fact, we only test against Clang under Linux. I will look into OS X coverage and testing but this is not top-priority right now (nevertheless I will try to do this before LIBXSMM 1.2). I guess you've noticed https://github.com/hfp/libxsmm/blob/master/Makefile.inc#L5 already?
