### ISSUE TITLE
Incorrect result in libxsmm

### ISSUE THREAD

**Issue by gnthibault** [hfp/libxsmm#187] opened 2017-07-19 13:34 UTC
Dear all,

Maybe I have done something wrong, but it looks like libxsmm return an incorrect result in the following code:

```
// STL
#include <cstdlib>
#include <algorithm>
#include <numeric>
#include <iostream>
// BLAS
#include <cblas.h>
// Libxsmm
#include <libxsmm.h>

// Compile using g++ -std=c++11 ./bug.cpp -lxsmm -lxsmmext -lblas -o ./bug
int main( int argc, char* argv[]) {
  int SIZEM=2, SIZEN=2,SIZEK=4;
  libxsmm_init();
  libxsmm_set_verbosity(2);
  auto print= [](double d){ std::cout<<d<<","; };
  const double alpha = 1.0;
  const double beta = 0.0;
  int SIZEA=SIZEM*SIZEK;
  int SIZEB=SIZEN*SIZEK;
  int SIZEC=SIZEM*SIZEN;
  const char TransA = 'N';
  const char TransB = 'N';
  const libxsmm_blasint M = SIZEM;
  const libxsmm_blasint N = SIZEN;
  const libxsmm_blasint K = SIZEK;
  const libxsmm_blasint lda = M;
  double *A = (double*)libxsmm_malloc(lda * K * sizeof(double));
  const libxsmm_blasint ldb = K;
  double *B = (double*)libxsmm_malloc(ldb * N * sizeof(double));
  const libxsmm_blasint ldc = M;
  double *C = (double*)libxsmm_malloc(ldc * N * sizeof(double));
  const libxsmm_gemm_prefetch_type prefetch =  LIBXSMM_PREFETCH_AUTO;
  const libxsmm_gemm_precision precision =
    libxsmm_gemm_precision::LIBXSMM_GEMM_PRECISION_F64; 
  libxsmm_bgemm_handle* pHandle = libxsmm_bgemm_handle_create(
  precision,
  M, N, K,
  NULL, NULL, NULL,
  NULL, NULL, NULL, NULL,
  &alpha,
  &beta,
  NULL,
  &prefetch,
  NULL);
  const CBLAS_ORDER layout = CblasColMajor;
  const CBLAS_TRANSPOSE TransA2 = CblasNoTrans;
  const CBLAS_TRANSPOSE TransB2 = CblasNoTrans;
  std::iota(A,A+SIZEA,0);
  std::iota(B,B+SIZEB,0);
  std::fill(C,C+SIZEC,0.0);
  libxsmm_bgemm_omp(pHandle, (const void*)A, (const void*)B, (void*) C, 1);
  cblas_dgemm(layout, TransA2, TransB2, M, N, K,
    1, A, lda, B, ldb, -1, C, ldc);
  std::cout<<"C should be zero: "<<std::endl;
  std::for_each(C,C+SIZEC,print);
  libxsmm_bgemm_handle_destroy(pHandle);
  libxsmm_free(A);
  libxsmm_free(B);
  libxsmm_free(C);
  libxsmm_finalize();
  return EXIT_SUCCESS;
}
```

**Comment by hfp** [comment] 2017-07-19 13:44
The same [root cause](https://github.com/hfp/libxsmm/issues/186#issuecomment-316390653) as for issue #186 applies here, therefore I am closing this issue and continue to use #186 to track the status.

**Closed by hfp** 2017-07-19 13:44 UTC
