### ISSUE TITLE
_Float128 duplicate definition with glibc 2.26

### ISSUE THREAD

**Issue by jewillco** [hfp/libxsmm#339] opened 2019-06-10 21:59 UTC
Glibc 2.26 and above have their own definition of `_Float128` that conflicts with LIBXSMM's version. To work around this, add an `#include` of `<features.h>` (with `_GNU_SOURCE` defined to avoid conflicting with other includes in other LIBXSMM files) into `libxsmm_macros.h` and check for `__GLIBC_PREREQ(2, 26)` as an additional condition to disable the `#define` of `_Float128`.

**Comment by hfp** [comment] 2019-06-11 05:56
Thank you for reporting this and also suggesting the workaround!

This definitition was once introduced as a workaround and now appears to be source of more trouble/maintenance. I will revise this, thank you again!

**Comment by hfp** [comment] 2019-06-19 17:31
How did you reproduce the issue?

I guess this was when compiling TF+LIBXSMM on an system with Glibc 2.26 (or newer), right?

**Comment by jewillco** [comment] 2019-06-19 17:36
Yes. I'm hitting with an internal build of the various tools and libraries,
but you should be able to see it with a compiler without _Float128 built in
but glibc 2.26 or above.

-- Jeremiah Willcock

**Comment by hfp** [comment] 2019-06-24 07:45
I added one more prerequisite before defining `_Float128` (there is now a check if `__SIZEOF_FLOAT128__` is not defined). Though, I cannot directly adopt the suggested workaround. At least not without wider tests on all supported platforms. I am still unable to reproduce the situation although I used Clang 3.8 (or earlier) without support for `_Float128` (or `__float128`) but with GLIBC newer than 2.26 (in fact 2.29).

Could you check if the problem is fixed?

**Comment by hfp** [comment] 2019-06-24 07:54
Hold on, the above won't work in this case. Let me give it one more try.

**Comment by hfp** [comment] 2019-06-24 08:47
This issue should be fixed now.

I guess it would further help if you had a proper release, right?

**Comment by hfp** [comment] 2019-07-15 13:51
The issue is (hopefully) resolved in [v1.13](https://github.com/hfp/libxsmm/releases/tag/1.13).

**Closed by hfp** 2019-07-15 13:51 UTC
